import type { HeroDefinition } from '../types/hero.js';

export const jin: HeroDefinition = {
  id: 'jin',
  name: 'Jin',
  description: 'A stealth thief, very sneaky but will give you big damage when possible.',
  hp: 100,
  physicalSkills: [
    {
      id: 'small_dart',
      name: 'Small Dart',
      description: 'Cast distance 0-1, 5 physical damage and stun opponent for 1 round.',
      minDistance: 0,
      maxDistance: 1,
      damage: 5,
      damageType: 'physical',
      selfDamage: 0,
      selfHeal: 0,
      appliesStatus: 'stunned',
      statusDuration: 1,
      selfStun: false,
      maxUses: -1,
      category: 'physical',
    },
  ],
  magicSkills: [
    {
      id: 'wind_walk',
      name: 'Wind Walk',
      description: 'Become invisible for 3 rounds. Immune to physical and targeted damage. Move 2 distance per round. Exit punch deals 15 physical damage.',
      minDistance: 0,
      maxDistance: 0,
      damage: 0,
      damageType: 'magic',
      selfDamage: 0,
      selfHeal: 0,
      selfStun: false,
      maxUses: -1,
      category: 'magic',
      special: ['wind_walk'],
    },
    {
      id: 'kuang',
      name: 'Kuang',
      description: 'Deal 50 magic damage to opponent (distance 0-1). Jin takes 10 magic damage. Can self-cast for 40 HP heal. One use only.',
      minDistance: 0,
      maxDistance: 1,
      damage: 50,
      damageType: 'magic',
      selfDamage: 10,
      selfHeal: 0,
      selfStun: false,
      maxUses: 1,
      category: 'magic',
      special: ['kuang_self_heal'],
    },
  ],
};
