import type { HeroDefinition } from '../types/hero.js';

export const nan: HeroDefinition = {
  id: 'nan',
  name: 'Nan',
  description: 'A very stinky character that damages nearby opponents with his odor.',
  hp: 100,
  passive: {
    id: 'stink_aura',
    name: 'Stink Aura',
    description: 'If opponent stays at distance 0 (same block), deal 10 magic damage per round.',
    trigger: 'distance_0',
    damage: 10,
    damageType: 'magic',
  },
  physicalSkills: [],
  magicSkills: [
    {
      id: 'magic_burn',
      name: 'Magic Burn',
      description: 'Cast distance 0, 15 magic damage, stuns opponent for 1 round.',
      minDistance: 0,
      maxDistance: 0,
      damage: 15,
      damageType: 'magic',
      selfDamage: 0,
      selfHeal: 0,
      appliesStatus: 'stunned',
      statusDuration: 1,
      selfStun: false,
      maxUses: 2,
      category: 'magic',
    },
    {
      id: 'call_fly',
      name: 'Call Fly',
      description: 'Call a fly to sting opponent anywhere on the map. 5 magic damage, heal self 5 HP.',
      minDistance: 0,
      maxDistance: 3,
      damage: 5,
      damageType: 'magic',
      selfDamage: 0,
      selfHeal: 5,
      selfStun: false,
      maxUses: -1,
      category: 'magic',
    },
  ],
};
