import type { HeroDefinition } from '../types/hero.js';

export const octopus: HeroDefinition = {
  id: 'octopus',
  name: 'Octopus',
  description: 'A fragile builder who trades mobility for sustain and a powerful tower.',
  hp: 80,
  physicalSkills: [
    {
      id: 'eat_legs',
      name: 'Eat Legs',
      description: 'Heal 5 HP. Can be used 8 times; after the 8th use, Octopus can no longer move.',
      minDistance: 0,
      maxDistance: 0,
      damage: 0,
      damageType: 'physical',
      selfDamage: 0,
      selfHeal: 5,
      selfStun: false,
      maxUses: 8,
      category: 'physical',
      special: ['eat_legs'],
    },
  ],
  magicSkills: [
    {
      id: 'build_tower',
      name: 'Build Tower',
      description: 'Build a stationary tower with 5 HP, magic immunity, and a ranged 0-1 physical attack for 25 damage.',
      minDistance: 0,
      maxDistance: 0,
      damage: 0,
      damageType: 'magic',
      selfDamage: 0,
      selfHeal: 0,
      selfStun: false,
      maxUses: -1,
      category: 'magic',
      special: ['build_tower'],
    },
  ],
  minion: {
    id: 'tower',
    name: 'Tower',
    description: 'A stationary magic-immune summon with a ranged 0-1 physical attack for 25 damage.',
    hp: 5,
    punchDamage: 25,
    punchCountsForStun: false,
    immuneTo: ['magic'],
    moveSpeed: 0,
    canMove: false,
    attackMinDistance: 0,
    attackMaxDistance: 1,
  },
};
